/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/dynamic/[id]': RouteRecordInfo<'/dynamic/[id]', '/dynamic/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/emoji/[id]': RouteRecordInfo<'/emoji/[id]', '/emoji/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/liveroom/[id]': RouteRecordInfo<'/liveroom/[id]', '/liveroom/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/lottery': RouteRecordInfo<'/lottery', '/lottery', Record<never, never>, Record<never, never>>,
    '/search/emoji': RouteRecordInfo<'/search/emoji', '/search/emoji', Record<never, never>, Record<never, never>>,
    '/search/garb': RouteRecordInfo<'/search/garb', '/search/garb', Record<never, never>, Record<never, never>>,
    '/search/general': RouteRecordInfo<'/search/general', '/search/general', Record<never, never>, Record<never, never>>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
    '/space/[id]': RouteRecordInfo<'/space/[id]', '/space/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/suit/[id]': RouteRecordInfo<'/suit/[id]', '/suit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/tool/lottie': RouteRecordInfo<'/tool/lottie', '/tool/lottie', Record<never, never>, Record<never, never>>,
    '/tool/svga': RouteRecordInfo<'/tool/svga', '/tool/svga', Record<never, never>, Record<never, never>>,
    '/tool/webp': RouteRecordInfo<'/tool/webp', '/tool/webp', Record<never, never>, Record<never, never>>,
    '/video/[id]': RouteRecordInfo<'/video/[id]', '/video/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
