/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/download': RouteRecordInfo<'/download', '/download', Record<never, never>, Record<never, never>>,
    '/dynamic/[id]': RouteRecordInfo<'/dynamic/[id]', '/dynamic/:id', { id: ParamValue<true> }, {
      id: ParamValue<false>
    }>,
    '/liveroom/[id]': RouteRecordInfo<'/liveroom/[id]', '/liveroom/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/lottery': RouteRecordInfo<'/lottery', '/lottery', Record<never, never>, Record<never, never>>,
    '/search/garb': RouteRecordInfo<'/search/garb', '/search/garb', Record<never, never>, Record<never, never>>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
    '/suit/[id]': RouteRecordInfo<'/suit/[id]', '/suit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
